/*
 * This file is part of HyperZoneLogin, licensed under the GNU Affero General Public License v3.0 or later.
 *
 * Copyright (C) ksqeib (庆灵) <ksqeib@qq.com>
 * Copyright (C) contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

package icu.h2l.login.cli.deploy

import java.io.File

/**
 * Shared logic for deploying a Paper/Purpur backend Minecraft server that sits
 * behind the Velocity proxy using modern forwarding.
 *
 * Generated files (relative to [dir])
 * ────────────────────────────────────
 *   server.properties                — standard Minecraft server properties
 *   eula.txt                         — EULA accepted (required to start Paper)
 *   config/paper-global.yml          — Paper 1.19+ global config (Velocity support)
 *   paper.yml                        — Paper ≤ 1.18 legacy config (Velocity support)
 *   spigot.yml                       — Spigot overrides (disable bungeecord mode)
 *   bukkit.yml                       — Bukkit baseline settings
 */
abstract class PaperServerDeployer(
    protected val dir: File,
    protected val port: Int,
    protected val paperVersion: String,
    protected val paperConfigMode: PaperConfigMode,
    protected val forwardingSecret: String,
    /** Short human-readable label used in log messages (e.g. "Lobby", "Game"). */
    protected val label: String,
    overwrite: Boolean,
) : ServerDeployer(overwrite) {

    override fun deploy() {
        println("[$label] Deploying into ${dir.path}")
        dir.mkdirs()

        writeFile(dir.resolve("server.properties"), serverProperties())
        writeFile(dir.resolve("eula.txt"), eulaTxt())
        if (usesModernPaperConfig()) {
            writeFile(dir.resolve("config/paper-global.yml"), paperGlobalYml())
            removeLegacyConfig(dir.resolve("paper.yml"))
        } else {
            writeFile(dir.resolve("paper.yml"), paperLegacyYml())
            removeLegacyConfig(dir.resolve("config/paper-global.yml"))
        }
        writeFile(dir.resolve("spigot.yml"), spigotYml())

        println()
    }

    private fun usesModernPaperConfig(): Boolean {
        if (paperConfigMode != PaperConfigMode.AUTO) {
            return paperConfigMode == PaperConfigMode.MODERN
        }
        if (!paperVersion.startsWith("1.")) {
            return true
        }

        val parts = paperVersion.substringBefore('-').split('.')
        val major = parts.getOrNull(0)?.toIntOrNull() ?: return true
        val minor = parts.getOrNull(1)?.toIntOrNull() ?: return true
        return major > 1 || (major == 1 && minor >= 19)
    }

    private fun removeLegacyConfig(file: File) {
        if (!file.exists()) {
            return
        }
        if (!overwrite) {
            println("  [keep]   ${file.path}  (belongs to another Paper config format; use --overwrite to remove)")
            return
        }
        file.delete()
        println("  [remove] ${file.path}")
    }

    enum class PaperConfigMode {
        AUTO,
        MODERN,
        LEGACY,
    }

    // --------------------------------------------------- shared config texts --

    private fun serverProperties(): String =
        """
        # Generated by HyperZoneLogin EasyDeploy
        # Minecraft server properties for the $label backend.
        #
        # IMPORTANT: online-mode MUST remain false because Velocity handles
        # authentication. Do NOT set it to true or player data will break.
        #
        # The server binds only on localhost (127.0.0.1) because it is not
        # meant to be reachable directly — all connections come via Velocity.

        server-ip=127.0.0.1
        server-port=$port
        online-mode=false
        enforce-secure-profile=false

        # General settings — adjust as needed
        max-players=100
        motd=HyperZoneLogin $label Server
        level-name=world
        gamemode=survival
        difficulty=normal
        spawn-protection=0
        view-distance=10
        simulation-distance=8
        allow-flight=false
        pvp=true
        enable-command-block=false
        white-list=false
        enforce-whitelist=false
        sync-chunk-writes=true
        """.trimIndent() + "\n"

    private fun eulaTxt(): String =
        """
        # By setting eula=true you indicate your agreement to the Minecraft EULA.
        # https://account.mojang.com/documents/minecraft_eula
        eula=true
        """.trimIndent() + "\n"

    /**
     * Paper 1.19+ global config with Velocity modern forwarding enabled.
     * See: https://docs.papermc.io/paper/reference/global-configuration
     */
    private fun paperGlobalYml(): String =
        """
        # Paper global configuration — generated by HyperZoneLogin EasyDeploy
        # Documentation: https://docs.papermc.io/paper/reference/global-configuration
        _version: 30
        proxies:
          bungee-cord:
            online-mode: false
          velocity:
            enabled: true
            online-mode: true
            secret: "$forwardingSecret"
        messages:
          no-permission: "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
          kick:
            connection-error: "&cAn unknown error occurred when attempting to connect you to the server. Please try again."
            flying-player: "&cFlying is not enabled on this server"
            flying-vehicle: "&cFlying is not enabled on this server"
        chunk-system:
          io-threads: -1
          worker-threads: -1
        item-validation:
          display-name: 8192
          lore-line: 8192
          resolve-selectors-in-books: false
        logging:
          deobfuscate-stacktraces: true
        misc:
          fix-entity-position-desync: true
          lag-compensate-block-breaking: true
          load-permissions-yml-before-plugins: true
          region-file-cache-size: 256
          use-alternative-luck-formula: false
          use-dimension-type-for-custom-spawners: false
        packet-limiter:
          all-packets:
            action: KICK
            interval: 7.0
            max-packet-rate: 500.0
          kick-message: "&cSent too many packets"
          overrides: {}
        player-auto-save:
          max-per-tick: -1
          rate: -1
        scoreboards:
          save-empty-scoreboard-teams: false
          track-plugin-scoreboards: false
        spam-limiter:
          incoming-packet-threshold: 300
          recipe-spam-increment: 1
          recipe-spam-limit: 20
          tab-spam-increment: 1
          tab-spam-limit: 500
        timings:
          enabled: true
          hidden-config-entries:
            - database
            - proxies.velocity.secret
          history-interval: 300
          history-length: 3600
          really-enabled: false
          server-name: Unknown Server
          server-name-privacy: false
          url: "https://timings.aikar.co/"
          verbose: true
        watchdog:
          early-warning-delay: 10000
          early-warning-every: 5000
        """.trimIndent() + "\n"

    /**
     * Paper ≤ 1.18 legacy `paper.yml` with Velocity support.
     * Kept so the same deployment works with older Paper builds.
     */
    private fun paperLegacyYml(): String =
        """
        # Paper legacy config (Paper 1.18 and older) — generated by HyperZoneLogin EasyDeploy
        verbose: false
        config-version: 28
        settings:
          velocity-support:
            enabled: true
            online-mode: true
            secret: "$forwardingSecret"
          use-display-name-in-quit-message: false
          rebrand:
            server-name: HyperZoneLogin $label
          async-chunks:
            threads: -1
        """.trimIndent() + "\n"

    private fun spigotYml(): String =
        """
        # Spigot configuration — generated by HyperZoneLogin EasyDeploy
        config-version: 12
        settings:
          # BungeeCord mode must be FALSE when using Velocity modern forwarding.
          bungeecord: false
          sample-count: 12
          player-shuffle: 0
          user-cache-size: 1000
          save-user-cache-on-stop-only: false
          moved-wrongly-threshold: 0.0625
          moved-too-quickly-multiplier: 10.0
          timeout: 60
          restart-on-crash: true
          restart-script: ./start.sh
          netty-threads: 4
          attribute:
            maxHealth:
              max: 2048.0
            movementSpeed:
              max: 2048.0
            attackDamage:
              max: 2048.0
        messages:
          whitelist: You are not whitelisted on this server!
          unknown-command: Unknown command. Type "/help" for help.
          server-full: The server is full!
          outdated-client: Outdated client! Please use {0}
          outdated-server: Outdated server! I'm still on {0}
          restart: Server is restarting
        world-settings:
          default:
            below-zero-generation-in-existing-chunks: true
            verbose: false
        """.trimIndent() + "\n"
}

