/*
 * This file is part of HyperZoneLogin, licensed under the GNU Affero General Public License v3.0 or later.
 *
 * Copyright (C) ksqeib (庆灵) <ksqeib@qq.com>
 * Copyright (C) contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

package icu.h2l.gradle

import java.io.File
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.Configuration
import org.gradle.api.artifacts.ResolvedArtifact
import org.gradle.api.attributes.Attribute
import org.gradle.api.tasks.Copy
import org.gradle.kotlin.dsl.named
import java.security.MessageDigest
import java.util.*

class HzlRuntimeDependenciesPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val needPackage = project.configurations.maybeCreate("needPackage").apply {
            isCanBeConsumed = false
            isCanBeResolved = false
            description = "Runtime libraries that should be downloaded and injected by HyperZoneLogin at startup."
        }

        val needPackageResolver = project.configurations.maybeCreate("needPackageResolver").apply {
            isCanBeConsumed = false
            isCanBeResolved = true
            extendsFrom(needPackage)
        }

        project.plugins.withId("org.jetbrains.kotlin.jvm") {
            configureMetadataGeneration(project, needPackageResolver)
        }
    }

    private fun configureMetadataGeneration(project: Project, resolver: Configuration) {
        val resourcePath =
            project.findProperty("hzl.runtimeDependencyResourcePath")?.toString()?.trim()?.takeIf { it.isNotEmpty() }
                ?: if (project.path == ":cli") "META-INF/hzl/cli-runtime-dependencies.properties" else null
                ?: "META-INF/hzl/runtime-dependencies.properties"
        val runtimeClasspath = project.configurations.named("runtimeClasspath").get()
        copyAttributes(runtimeClasspath, resolver)

        val outputFile = project.layout.buildDirectory.file("generated/hzl/runtime-dependencies/${resourcePath.replace('/', File.separatorChar)}")

        val generateTask = project.tasks.register("generateRuntimeDependencyMetadata") {
            inputs.files(resolver)
            outputs.file(outputFile)

            doLast {
                val artifacts = resolver.resolvedConfiguration.resolvedArtifacts
                    .filter(::isExternalJar)
                    .sortedBy { artifactId(it) }

                val properties = Properties().apply {
                    setProperty("count", artifacts.size.toString())
                }

                artifacts.forEachIndexed { index, artifact ->
                    val moduleId = artifact.moduleVersion.id
                    properties.setProperty("dependency.$index.group", moduleId.group)
                    properties.setProperty("dependency.$index.name", artifact.name)
                    properties.setProperty("dependency.$index.version", moduleId.version)
                    properties.setProperty("dependency.$index.sha256", sha256(artifact))
                }

                val file = outputFile.get().asFile
                file.parentFile.mkdirs()
                file.outputStream().use { out ->
                    properties.store(out, "Generated by icu.h2l.runtime-dependencies")
                }
            }
        }

        project.tasks.named<Copy>("processResources") {
            from(generateTask) {
                into(resourcePath.substringBeforeLast('/', ""))
                rename { resourcePath.substringAfterLast('/') }
            }
        }
    }

    private fun copyAttributes(source: Configuration, target: Configuration) {
        source.attributes.keySet().forEach { key ->
            @Suppress("UNCHECKED_CAST")
            val typedKey = key as Attribute<Any>
            val value = source.attributes.getAttribute(typedKey) ?: return@forEach
            target.attributes.attribute(typedKey, value)
        }
    }

    private fun isExternalJar(artifact: ResolvedArtifact): Boolean {
        val moduleId = artifact.moduleVersion.id
        return artifact.extension == "jar" && moduleId.group != "unspecified"
    }

    private fun artifactId(artifact: ResolvedArtifact): String {
        val moduleId = artifact.moduleVersion.id
        return "${moduleId.group}:${artifact.name}:${moduleId.version}"
    }

    private fun sha256(artifact: ResolvedArtifact): String {
        val digest = MessageDigest.getInstance("SHA-256")
        artifact.file.inputStream().use { input ->
            val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
            while (true) {
                val read = input.read(buffer)
                if (read == -1) {
                    break
                }
                digest.update(buffer, 0, read)
            }
        }
        return Base64.getEncoder().encodeToString(digest.digest())
    }
}

